import { Card, Paragraph } from "../components";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Text Truncate Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Card>
          <h1>Lorem ipsum dolor sit amet</h1>
          <Paragraph>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ultricies ipsum at feugiat tempor. Quisque tortor urna, pellentesque sit amet consequat nec, lacinia a orci. Maecenas vulputate suscipit nisl, eu ultrices enim laoreet sed. Sed urna est, iaculis sit amet aliquet eu, molestie quis sem. Donec non elementum mi, eget varius ex. Integer et rutrum neque. Sed varius malesuada vulputate. Sed et eleifend felis. Nunc vulputate neque sit amet sem auctor porttitor. Maecenas ac dui in risus pellentesque facilisis. Nullam auctor mollis varius. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur elementum enim libero, id luctus velit hendrerit eget. Sed rutrum nunc in posuere mollis. Etiam felis risus, fringilla vel elit vitae, tincidunt facilisis mauris.
          </Paragraph>
        </Card>
      </main>
    </>
  );
}
